engines:
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 40

  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "cleancode,unusedcode,codesize,design"
ratings:
  paths:
  - "lib/**.php"
exclude_paths:
- tests/